//general
export const GET_PUBLIC_DATA_REQUEST = "GET_PUBLIC_DATA_REQUEST";
export const GET_PUBLIC_DATA_RESPONSE = "GET_PUBLIC_DATA_RESPONSE";

export const GET_SLIDESHOW_DATA_REQUEST = "GET_SLIDESHOW_DATA_REQUEST";
export const INITIAL_CALL_REQUEST = "INITIAL_CALL_REQUEST";

export const GET_USER_DATA_RESPONSE = "GET_USER_DATA_RESPONSE";
//article
export const GET_ARTICLE_DATA_REQUEST = "GET_ARTICLE_DATA_REQUEST";
export const GET_ARTICLE_DATA_RESPONSE = "GET_ARTICLE_DATA_RESPONSE";
